### ISSUE TITLE
Registry update contact

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/ga4gh-registry#13]
Hi, 

I don't believe the contact `Jeremy Adams [jeremy.adams@ga4gh.org](mailto:jeremy.adams@ga4gh.org)` in the readme.md is up-to-date. Who is the current maintainer for this service. 

https://github.com/ga4gh/ga4gh-registry/blob/main/README.md?plain=1#L50

We wish to make a correction as detailed in https://github.com/dockstore/dockstore/issues/5803

**Comment by denis-yuen** [comment]
FYI @jb-adams if you happen to know

**Comment by denis-yuen** [comment]
Tagging @yash-puligundla or @ga4gh/ga4gh-tech-team

**Comment by jppay** [comment]
This issue has been picked up by the GA4GH tech team and the registry entry would be updated. More details to be shared.

**Comment by jppay** [comment]
Issue fixed. Entry updated.

**Comment by denis-yuen** [comment]
Thanks!
